### ISSUE TITLE
Update GSA's developer hub:

### ISSUE THREAD

**Issue by rdgsa** [18F/API-All-the-X#231]
Here is the current GSA developer hub:

https://open.gsa.gov/

**Comment by kinlane** [comment]
Excellent work! Loving the momentum.

**Comment by rdgsa** [comment]
@gbinal This is still open.

**Comment by gbinal** [comment]
done - https://github.com/18F/API-All-the-X/commit/a6b2bfd98d730ebecb2d8627cc1b6885c7efd10d
